### ISSUE TITLE
common js 如何和 业务模块 js 进行分离

### ISSUE THREAD

**Issue by weijianfeng** [pukaicom/reactNativeBundleBreak#1]
请问，分离两部分 js 代码有什么思路么。看了您的文章，可以打包之后，然后比对的方式，另外还有什么别的思路了么。

**Comment by pukaicom** [comment]
bundle打包进去一些公共的部分进去，我们做的是把这部分提取出来形成common.js 可以大幅度减小包体积，至于你说的如何做到业务和公共部分的完全分离，你可以使用unbundle命令打包试一下，这个可以将每一个模块都单独生成一个js文件，可以参考工程ReactNativeBsdiff

**Comment by weijianfeng** [comment]
OK, 谢谢
