### ISSUE TITLE
如果有两个业务包的时候，需要相互切换，此时会报找不到某个方法的错误。

### ISSUE THREAD

**Issue by chen1kun** [pukaicom/reactNativeBundleBreak#3]
请问下有预加载reactinstancemanager，两个业务包切换的demo吗

**Comment by pukaicom** [comment]
切换后的 bundle必须得读入内存与react View建立绑定关系

**Comment by chen1kun** [comment]
比如我们现在6666是一个业务，7777是一个业务，当预加载基础包后，require (6666)可以加载到该业务，当退出页面在点击7777业务后就会报找不到对应方法的错误，但是退出后再点击require 6666是没有问题的。 你的意思是，我在切换业务的时候使用反射jsloader去调用loadscript读入内存吗？

**Comment by pukaicom** [comment]
你确认一下 7777 里的某些方法代号数字ID 与666是否重复了

**Comment by chen1kun** [comment]
好的，我先排查一下，谢谢啦

**Comment by chen1kun** [comment]
可以了~~ 是因为moduleId有重复的导致requireModule的时候报错了。

**Comment by chen1kun** [comment]
请问下你们拆包后，bundle包是放在assets下面还是放在文件里的呢

**Comment by pukaicom** [comment]
目前我会在asset 下面放一个备份 然后在启动的时候判断手机 local 路径下有没有，没有的话复制过去，然后加载
